export const Routes = {
  WELCOME: 'WELCOME',
  HOMESCREEN: 'HOMESCREEN',
  MOVIELIST: 'MOVIELIST',
  ADDNEWLIST: 'ADDNEWLIST',
  MAIN: 'MAIN',
  HOME: 'HOME',
  NEWHOT: 'NEWHOT',
  SEARCH: 'SEARCH',
  MYLIST: 'MYLIST',
  PROFILE: 'PROFILE',
  MOVIEDETAIL: 'MOVIEDETAIL',
  ARTISTDETAIL: 'ARTISTDETAIL',
} as const;

export type RouteName = keyof typeof Routes;
